name: ci

on:
  workflow_dispatch:

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-app
          key: ${{ runner.os }}-buildx-app-web-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-buildx-app-web
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: apps/web/Dockerfile
          tags: |
            nickchengw/gw-ci-web-test:latest
            nickchengw/gw-ci-web-test:${{ github.sha }}
          build-args: |
            TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM=${{ vars.TURBO_TEAM }}
          cache-from: type=local,src=/tmp/.buildx-cache-app
          cache-to: type=local,dest=/tmp/.buildx-cache-app-new,mode=max
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-app  
          mv /tmp/.buildx-cache-app-new /tmp/.buildx-cache-app
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-app
          key: ${{ runner.os }}-buildx-app-docs-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-buildx-app-docs
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: apps/docs/Dockerfile
          tags: |
            nickchengw/gw-ci-docs-test:latest
            nickchengw/gw-ci-docs-test:${{ github.sha }}
          build-args: |
            TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM=${{ vars.TURBO_TEAM }}
          cache-from: type=local,src=/tmp/.buildx-cache-app
          cache-to: type=local,dest=/tmp/.buildx-cache-app-new,mode=max
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-app  
          mv /tmp/.buildx-cache-app-new /tmp/.buildx-cache-app
