name: ci

on:
  workflow_dispatch:

jobs:
  build-docker:
    name: Build
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-app
          key: ${{ runner.os }}-buildx-app-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-app
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: apps/web/Dockerfile
          tags: user/app:latest
          build-args: |
            TURBO_TOKEN=${{ env.TURBO_TOKEN }}
            TURBO_TEAM=${{ env.TURBO_TEAM }}
          cache-from: type=local,src=/tmp/.buildx-cache-app
          cache-to: type=local,dest=/tmp/.buildx-cache-app-new,mode=max
      - name: APP::Move cache
        run: |
          rm -rf /tmp/.buildx-cache-app  
          mv /tmp/.buildx-cache-app-new /tmp/.buildx-cache-app
