name: image tag test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        type: string

jobs:
  workflow:
    name: Test
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ inputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up docker image tag
        id: get-tag
        run: |
          echo "IMAGE_TAG=$(git log -n 1 --pretty=format:'%h' --abbrev=10)" >> $GITHUB_OUTPUT
      - name: Echo tag
        run: |
          echo ${{ inputs.tag || steps.get-tag.outputs.IMAGE_TAG }}
